name: Test

on:
  push:
    paths:
      - "**.ml"
      - "**.mli"
      - "dune"
      - "dune-project"
      - "dune-workspace"
      - "**.opam"
      - ".github/workflows/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache OPAM dependencies
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v3

      - name: List opam
        uses: ocaml/setup-ocaml/lint-opam@v3
